部分错别字和标点符号错误
Awesome-HarmonyOS/HarmonyOS pull request #81
Opened 2019-08-13 08:45 UTC by laosanyuan

标点符号错误，"的"用法错误

2019-08-15 02:44 UTC, rfyiamcool commented
What bike? I asked you why you wanted a bike.

2019-08-15 05:53 UTC, lixp185 commented
hahaha...

2019-08-15 06:16 UTC, uuvccc requested changes

2019-08-15 06:16 UTC, uuvccc commented on Huawei_LiteOS/README.md
> -同时提供端云协同能力，集成了LwM2M、CoAP、mbedtls、LwIP全套IoT互联协议栈，且在LwM2M的基础上，提供了AgentTiny模块，用户只需关注自身的应用，而不必关注LwM2M实现细节，直接使用AgentTiny封装的接口即可简单快速实现与云平台安全可靠的连接。
我觉得这里的“连接”是名词，所以“可靠的连接”是没问题的。

2019-08-15 09:14 UTC, laosanyuan commented
> What bike? I asked you why you wanted a bike.

真牛逼

2019-08-17 02:59 UTC, dyq94310 commented
疯狂修typo

2019-08-17 06:41 UTC, wushuangForGit commented on Huawei_LiteOS/README.md
> -同时提供端云协同能力，集成了LwM2M、CoAP、mbedtls、LwIP全套IoT互联协议栈，且在LwM2M的基础上，提供了AgentTiny模块，用户只需关注自身的应用，而不必关注LwM2M实现细节，直接使用AgentTiny封装的接口即可简单快速实现与云平台安全可靠的连接。
是动词！

2019-08-19 05:44 UTC, mushipu1988 commented
有病句

2019-08-19 06:30 UTC, DavidHux commented
新语法已经取消“的、地、得”的区别，以前用‘地’，‘得’的地方都可以用‘的’。所以，huawei没错！！！

2019-08-19 08:25 UTC, thingRoll commented
什么都没有，看啥

2019-08-20 07:18 UTC, helloboboli commented
> What bike? I asked you why you wanted a bike.
go two steps,  go two steps if ok

2019-08-21 03:22 UTC, redcomma commented
啥都没有，看什么？

2019-08-22 09:10 UTC, cdyangzhenyu commented
好歹也是咱大国产操作系统，能不能严肃点

2019-08-23 08:57 UTC, closed without merging

2019-10-22 09:16 UTC, wushuangForGit commented
fuck you




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"martinboboli"<notifications@github.com&gt;;
发送时间:&nbsp;2019年8月20日(星期二) 下午3:19
收件人:&nbsp;"Awesome-HarmonyOS/HarmonyOS"<HarmonyOS@noreply.github.com&gt;;
抄送:&nbsp;"头发乱了"<64941167@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Awesome-HarmonyOS/HarmonyOS] 部分错别字和标点符号错误 (#81)



 
What bike? I asked you why you wanted a bike.
 go two steps,  go two steps if ok
  
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.